### Register
GET http://localhost:3000/register

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "rakkaalhazimi@gmail.com",
    "password": "@Tenyom1234",
    "confirmPassword": "@Tenyom1234",
    "fullName": "Rakka",
    "gender": "male"
}


### Login

GET http://localhost:3000/login

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "rakkaalhazimi@gmail.com",
    "password": "@Tenyom1234"
}

### Profile

GET http://localhost:3000/Profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJha2thYWxoYXppbWlAZ21haWwuY29tIiwiaWF0IjoxNjY1ODE0OTk0LCJleHAiOjE2NjU4MTUyOTR9.OB_5ohUzXcJ0WOK1e3JUNjWN8ZujR6j2S9BrkXohm2A


###